"use client";

import { Activity, AlertTriangle, ArrowLeft, ArrowRight, ArrowRightLeft, CheckCircle2, ChevronDown, ChevronRight, Clock3, Database, Filter, LayoutDashboard, LoaderCircle, LockKeyhole, LogOut, RefreshCw, Search, ShieldCheck, UsersRound, WalletCards, XCircle } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useRef, useState } from "react";
import styles from "./transfers.module.css";

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:4000/api/v1";
type Party = { userId: string; fullName: string; maskedEmail: string; maskedPhone?: string; userStatus: string; walletId: string; walletNumber: string; walletStatus: string };
type Item = { id: string; reference: string; amountMinor: string; currency: string; note: string | null; status: string; failureCode: string | null; initiatedAt: string; completedAt: string | null; sender: Party; receiver: Party; initiator: { userId: string; fullName: string }; jobs: { health: string; count: number } };
type List = { items: Item[]; nextCursor: string | null };
type Details = {
  transfer: { id: string; reference: string; idempotencyKey: string; amountMinor: string; currency: string; note: string | null; status: string; failureCode: string | null; initiatedAt: string; completedAt: string | null; failedAt: string | null; reversedAt: string | null; createdAt: string; updatedAt: string; senderBalanceBeforeMinor: string | null; senderBalanceAfterMinor: string | null; receiverBalanceBeforeMinor: string | null; receiverBalanceAfterMinor: string | null };
  sender: Party; receiver: Party; initiator: { userId: string; fullName: string };
  lifecycle: { id: string; previousStatus: string | null; newStatus: string; source: string; reasonCode: string | null; actorName: string | null; sourceJobId: string | null; occurredAt: string }[];
  ledgerTransactions: { id: string; type: string; referenceId: string; description: string | null; reversalOfId: string | null; postedAt: string }[];
  ledgerEntries: { id: string; ledgerTransactionId: string; entryType: string; amountMinor: string; currency: string; account: { id: string; code: string; type: string; walletId: string | null; name: string; currency: string; status: string }; createdAt: string }[];
  jobs: { id: string; type: string; status: string; attempts: number; maxAttempts: number; availableAt: string; lastAttemptAt: string | null; completedAt: string | null; lastErrorCode: string | null; lastErrorMessage: string | null; createdAt: string; updatedAt: string }[];
  audits: { id: string; actorType: string; actorName: string; action: string; outcome: string; severity: string; sourceJobId: string | null; metadata: Record<string, unknown> | null; occurredAt: string }[];
  integrityIndicators: string[];
};
type Filters = { search: string; participant: string; initiatorUserId: string; status: string; failureCode: string; currency: string; amountMinMinor: string; amountMaxMinor: string; initiatedFrom: string; initiatedTo: string; jobHealth: string };
const emptyFilters: Filters = { search: "", participant: "", initiatorUserId: "", status: "", failureCode: "", currency: "", amountMinMinor: "", amountMaxMinor: "", initiatedFrom: "", initiatedTo: "", jobHealth: "" };

function money(value: string | null, currency: string) { return value === null ? "—" : new Intl.NumberFormat("en-IN", { style: "currency", currency: currency.trim() }).format(Number(value) / 100) }
function date(value: string | null) { return value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—" }
function label(value: string) { return value.replaceAll("_", " ") }
function messageFrom(body: unknown, fallback: string) { if (body && typeof body === "object" && "message" in body) { const message = (body as { message: unknown }).message; return Array.isArray(message) ? message.join(". ") : typeof message === "string" ? message : fallback } return fallback }
function Status({ value }: { value: string }) { return <span className={`${styles.status} ${styles[value.toLowerCase()]}`}>{label(value)}</span> }
function Brand() { return <span className={styles.brand}><span className={styles.mark}><i /><i /></span>LedgerFlow <small>OPS</small></span> }

export default function TransferMonitoringPage() {
  const router = useRouter(); const started = useRef(false);
  const [token, setToken] = useState(""); const [filters, setFilters] = useState<Filters>(emptyFilters); const [advanced, setAdvanced] = useState(false);
  const [list, setList] = useState<List | null>(null); const [selected, setSelected] = useState<Details | null>(null); const [tab, setTab] = useState<"overview" | "lifecycle" | "ledger" | "jobs" | "audit">("overview");
  const [loading, setLoading] = useState(true); const [detailsLoading, setDetailsLoading] = useState(false); const [loadingMore, setLoadingMore] = useState(false); const [denied, setDenied] = useState(false); const [error, setError] = useState("");

  function params(values: Filters, cursor?: string) { const query = new URLSearchParams({ limit: "20" }); Object.entries(values).forEach(([key, value]) => { if (value.trim()) query.set(key, value.trim()) }); if (cursor) query.set("cursor", cursor); return query }
  async function load(accessToken: string, values: Filters, cursor?: string, append = false) { const response = await fetch(`${API}/admin/transfers?${params(values, cursor)}`, { headers: { Authorization: `Bearer ${accessToken}` }, cache: "no-store" }); const body = await response.json().catch(() => null); if (response.status === 401) { router.replace("/login"); return } if (response.status === 403) { setDenied(true); return } if (!response.ok) throw new Error(messageFrom(body, "Transfers could not be loaded.")); setList(current => append && current ? { items: [...current.items, ...body.items], nextCursor: body.nextCursor } : body) }
  async function details(id: string, accessToken = token) { setDetailsLoading(true); setError(""); try { const response = await fetch(`${API}/admin/transfers/${id}`, { headers: { Authorization: `Bearer ${accessToken}` }, cache: "no-store" }); const body = await response.json().catch(() => null); if (response.status === 401) { router.replace("/login"); return } if (response.status === 403) { setDenied(true); return } if (!response.ok) throw new Error(messageFrom(body, "Transfer details could not be loaded.")); setSelected(body); setTab("overview") } catch (value) { setError(value instanceof Error ? value.message : "Transfer details could not be loaded.") } finally { setDetailsLoading(false) } }
  useEffect(() => { if (started.current) return; started.current = true; void (async () => { try { const response = await fetch(`${API}/auth/refresh`, { method: "POST", credentials: "include" }); if (!response.ok) { router.replace("/login"); return } const body = await response.json(); setToken(body.accessToken); await load(body.accessToken, emptyFilters) } catch (value) { setError(value instanceof Error ? value.message : "LedgerFlow is unavailable.") } finally { setLoading(false) } })() }, [router]);
  async function search(event?: FormEvent, next = filters) { event?.preventDefault(); setLoading(true); setError(""); setSelected(null); try { await load(token, next) } catch (value) { setError(value instanceof Error ? value.message : "Transfer search failed.") } finally { setLoading(false) } }
  function change(patch: Partial<Filters>, auto = true) { const next = { ...filters, ...patch }; setFilters(next); if (auto) void search(undefined, next) }
  async function loadMore() { if (!list?.nextCursor) return; setLoadingMore(true); try { await load(token, filters, list.nextCursor, true) } catch (value) { setError(value instanceof Error ? value.message : "More transfers could not be loaded.") } finally { setLoadingMore(false) } }
  async function logout() { await fetch(`${API}/auth/logout`, { method: "POST", credentials: "include" }).catch(() => undefined); router.replace("/login") }
  if (denied) return <main className={styles.center}><LockKeyhole /><h1>Administrator access required</h1><Link href="/dashboard">Return to dashboard</Link></main>;
  if (loading && !list) return <main className={styles.center}><LoaderCircle className={styles.spin} /><h1>Loading transfer monitoring…</h1></main>;
  const indicators = selected?.integrityIndicators ?? [];
  return <main className={styles.page}>
    <aside className={styles.sidebar}><Brand /><p>ADMINISTRATION</p><nav><Link href="/admin"><LayoutDashboard />Dashboard</Link><Link href="/admin/users"><UsersRound />User management</Link><Link href="/admin/wallets"><WalletCards />Wallet management</Link><Link className={styles.active} href="/admin/transfers"><ArrowRightLeft />Transfer monitoring</Link><Link href="/admin/ledger"><Database />Ledger &amp; reconciliation</Link></nav><div className={styles.protection}><ShieldCheck /><span><strong>Investigation only</strong><small>No transfer mutations</small></span></div><button onClick={() => void logout()}><LogOut />Sign out</button></aside>
    <section className={styles.content}><header className={styles.header}><div><Link href="/admin"><ArrowLeft />Admin dashboard</Link><span className={styles.kicker}>TRANSFER OPERATIONS</span><h1>Transfer monitoring</h1><p>Trace lifecycle, ledger evidence, and asynchronous processing health.</p></div><button onClick={() => void search()}><RefreshCw />Refresh</button></header>
      {error && <div className={styles.error}><AlertTriangle /><span>{error}</span><button onClick={() => setError("")}><XCircle /></button></div>}
      <section className={styles.filters}><form onSubmit={search}><Search /><input value={filters.search} onChange={e => change({ search: e.target.value }, false)} placeholder="Exact transfer ID or reference" /><button>Search</button></form><select value={filters.status} onChange={e => change({ status: e.target.value })}><option value="">All statuses</option><option>PENDING</option><option>COMPLETED</option><option>FAILED</option><option>REVERSED</option></select><select value={filters.jobHealth} onChange={e => change({ jobHealth: e.target.value })}><option value="">All job health</option><option>HEALTHY</option><option>MISSING</option><option>FAILED</option><option>RETRYING</option></select><button className={styles.advancedButton} onClick={() => setAdvanced(!advanced)}><Filter />Filters<ChevronDown /></button></section>
      {advanced && <form className={styles.advanced} onSubmit={search}><label>Participant wallet / user<input value={filters.participant} onChange={e => change({ participant: e.target.value }, false)} /></label><label>Initiator user ID<input value={filters.initiatorUserId} onChange={e => change({ initiatorUserId: e.target.value }, false)} /></label><label>Failure code<input value={filters.failureCode} onChange={e => change({ failureCode: e.target.value }, false)} /></label><label>Currency<input maxLength={3} value={filters.currency} onChange={e => change({ currency: e.target.value.toUpperCase() }, false)} /></label><label>Minimum minor units<input type="number" min="1" value={filters.amountMinMinor} onChange={e => change({ amountMinMinor: e.target.value }, false)} /></label><label>Maximum minor units<input type="number" min="1" value={filters.amountMaxMinor} onChange={e => change({ amountMaxMinor: e.target.value }, false)} /></label><label>Initiated from<input type="datetime-local" value={filters.initiatedFrom} onChange={e => change({ initiatedFrom: e.target.value }, false)} /></label><label>Initiated to<input type="datetime-local" value={filters.initiatedTo} onChange={e => change({ initiatedTo: e.target.value }, false)} /></label><div><button type="button" onClick={() => { setFilters(emptyFilters); void search(undefined, emptyFilters) }}>Clear</button><button>Apply filters</button></div></form>}
      <p className={styles.readonly}><LockKeyhole />This screen is read-only. Retries, reversals, balance edits, and status changes belong to separate controlled workflows.</p>
      <section className={styles.workspace}><article className={styles.listPanel}><div className={styles.listHead}><span><strong>{list?.items.length ?? 0}</strong> transfers shown</span><small>Newest first</small></div><div className={styles.tableWrap}><table><thead><tr><th>Transfer</th><th>Participants</th><th>Amount</th><th>Status</th><th>Jobs</th><th>Initiated</th><th /></tr></thead><tbody>{list?.items.map(item => <tr key={item.id} onClick={() => void details(item.id)} className={selected?.transfer.id === item.id ? styles.selectedRow : ""}><td><strong>{item.reference}</strong><small>{item.id.slice(0, 8)}…</small></td><td><strong>{item.sender.fullName} <ArrowRight /> {item.receiver.fullName}</strong><small>{item.sender.walletNumber} → {item.receiver.walletNumber}</small></td><td><strong>{money(item.amountMinor, item.currency)}</strong></td><td><Status value={item.status} />{item.failureCode && <small>{label(item.failureCode)}</small>}</td><td><Status value={item.jobs.health} /><small>{item.jobs.count} jobs</small></td><td>{date(item.initiatedAt)}</td><td><ChevronRight /></td></tr>)}</tbody></table>{loading && <div className={styles.loadingLine}><LoaderCircle className={styles.spin} />Loading…</div>}{!loading && list?.items.length === 0 && <div className={styles.empty}><ArrowRightLeft /><h3>No transfers found</h3><p>Adjust the investigation filters.</p></div>}</div>{list?.nextCursor && <button className={styles.loadMore} onClick={() => void loadMore()} disabled={loadingMore}>{loadingMore ? "Loading…" : "Load more transfers"}</button>}</article>
        <aside className={styles.detailPanel}>{detailsLoading && <div className={styles.detailEmpty}><LoaderCircle className={styles.spin} />Loading evidence…</div>}{!detailsLoading && !selected && <div className={styles.detailEmpty}><Activity /><h3>Select a transfer</h3><p>Review its complete operational evidence.</p></div>}{!detailsLoading && selected && <><div className={styles.detailHead}><span><ArrowRightLeft /></span><div><small>TRANSFER</small><h2>{selected.transfer.reference}</h2><p>{selected.sender.fullName} → {selected.receiver.fullName}</p></div><Status value={selected.transfer.status} /></div>{indicators.length > 0 && <div className={styles.warning}><AlertTriangle /><span><strong>{indicators.length} integrity indicator{indicators.length === 1 ? "" : "s"}</strong><small>{indicators.map(label).join(" · ")}</small></span></div>}{indicators.length === 0 && <div className={styles.healthy}><CheckCircle2 />No integrity inconsistencies detected</div>}<nav className={styles.tabs}>{(["overview", "lifecycle", "ledger", "jobs", "audit"] as const).map(value => <button key={value} className={tab === value ? styles.current : ""} onClick={() => setTab(value)}>{value}</button>)}</nav><div className={styles.detailBody}>
          {tab === "overview" && <><section className={styles.amountCard}><small>TRANSFER AMOUNT</small><strong>{money(selected.transfer.amountMinor, selected.transfer.currency)}</strong><span><Status value={selected.transfer.status} /><small>{date(selected.transfer.initiatedAt)}</small></span></section><h3>Parties</h3><div className={styles.partyGrid}>{[["Sender", selected.sender], ["Receiver", selected.receiver]].map(([role, party]) => { const p = party as Party; return <div key={role as string}><small>{role as string}</small><strong>{p.fullName}</strong><span>{p.maskedEmail} · {p.maskedPhone}</span><code>{p.walletNumber}</code><span><Status value={p.userStatus} /> <Status value={p.walletStatus} /></span></div> })}</div><h3>Balance snapshots</h3><div className={styles.infoGrid}><div><small>Sender before</small><strong>{money(selected.transfer.senderBalanceBeforeMinor, selected.transfer.currency)}</strong></div><div><small>Sender after</small><strong>{money(selected.transfer.senderBalanceAfterMinor, selected.transfer.currency)}</strong></div><div><small>Receiver before</small><strong>{money(selected.transfer.receiverBalanceBeforeMinor, selected.transfer.currency)}</strong></div><div><small>Receiver after</small><strong>{money(selected.transfer.receiverBalanceAfterMinor, selected.transfer.currency)}</strong></div></div><div className={styles.metadata}><p><small>Transfer ID</small><code>{selected.transfer.id}</code></p><p><small>Idempotency key</small><code>{selected.transfer.idempotencyKey}</code></p><p><small>Initiator</small><span>{selected.initiator.fullName} · {selected.initiator.userId}</span></p><p><small>Note</small><span>{selected.transfer.note || "No note"}</span></p><p><small>Failure code</small><span>{selected.transfer.failureCode || "None"}</span></p></div></>}
          {tab === "lifecycle" && <div className={styles.timeline}>{selected.lifecycle.map(event => <div key={event.id}><span><Clock3 /></span><section><strong>{event.previousStatus ? label(event.previousStatus) : "Created"} <ArrowRight /> {label(event.newStatus)}</strong><p>{label(event.source)}{event.reasonCode ? ` · ${label(event.reasonCode)}` : ""}</p><small>{event.actorName || "System"} · {date(event.occurredAt)}</small>{event.sourceJobId && <code>Job {event.sourceJobId}</code>}</section></div>)}</div>}
          {tab === "ledger" && <><h3>Ledger transactions</h3>{selected.ledgerTransactions.map(transaction => <section className={styles.ledgerCard} key={transaction.id}><div><Database /><span><strong>{label(transaction.type)}</strong><small>{transaction.description || "No description"}</small><code>{transaction.id}{transaction.reversalOfId ? ` · reverses ${transaction.reversalOfId}` : ""}</code></span></div>{selected.ledgerEntries.filter(entry => entry.ledgerTransactionId === transaction.id).map(entry => <p key={entry.id}><Status value={entry.entryType} /><span><strong>{entry.account.name}</strong><small>{entry.account.code} · {entry.account.type}</small></span><b>{money(entry.amountMinor, entry.currency)}</b></p>)}</section>)}{selected.ledgerTransactions.length === 0 && <p className={styles.emptyText}>No ledger transaction is linked to this transfer.</p>}</>}
          {tab === "jobs" && <div className={styles.cardList}>{selected.jobs.map(job => <section key={job.id}><header><strong>{label(job.type)}</strong><Status value={job.status} /></header><p>Attempts <b>{job.attempts}/{job.maxAttempts}</b> · available {date(job.availableAt)}</p><small>Last attempt {date(job.lastAttemptAt)} · completed {date(job.completedAt)}</small>{(job.lastErrorCode || job.lastErrorMessage) && <div className={styles.jobError}><strong>{job.lastErrorCode || "PROCESSING ERROR"}</strong><p>{job.lastErrorMessage || "No safe error message recorded."}</p></div>}<code>{job.id}</code></section>)}{selected.jobs.length === 0 && <p className={styles.emptyText}>No background jobs are linked to this transfer.</p>}</div>}
          {tab === "audit" && <div className={styles.cardList}>{selected.audits.map(audit => <section key={audit.id}><header><strong>{label(audit.action)}</strong><Status value={audit.outcome} /></header><p>{audit.actorName} · {label(audit.actorType)} · {label(audit.severity)}</p><small>{date(audit.occurredAt)}</small>{audit.metadata && <pre>{JSON.stringify(audit.metadata, null, 2)}</pre>}</section>)}{selected.audits.length === 0 && <p className={styles.emptyText}>No audit records are linked to this transfer.</p>}</div>}
        </div></>}</aside></section>
    </section>
  </main>
}
