ALTER TYPE ledger_account_type
  ADD VALUE IF NOT EXISTS 'SYSTEM_ADJUSTMENT';
ALTER TYPE ledger_transaction_type
  ADD VALUE IF NOT EXISTS 'TRANSFER_REVERSAL';
ALTER TYPE ledger_transaction_type
  ADD VALUE IF NOT EXISTS 'LEDGER_ADJUSTMENT';
