import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { randomBytes, randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { DatabaseService } from "../database/database.service";
import { AdjustmentDecisionDto, CreateAdjustmentDto, FindingActionDto, LedgerQueryDto, StartReconciliationDto } from "./dto/ledger.dto";
type Role="CUSTOMER"|"ADMIN";

@Injectable()
export class AdminLedgerService {
  constructor(private readonly database:DatabaseService){}

  async overview(adminId:string,role:Role,query:LedgerQueryDto){
    await this.assertAdmin(this.database,adminId,role); const search=query.search?.trim()??"";
    const [summary,trial,entries,wallets,runs,findings,adjustments,accounts]=await Promise.all([
      this.database.query(`SELECT COUNT(DISTINCT lt.id)::INT AS transactions,COUNT(le.id)::INT AS entries,COUNT(DISTINCT le.currency)::INT AS currencies,COUNT(DISTINCT lt.id) FILTER(WHERE x.debits<>x.credits)::INT AS unbalanced FROM ledger_transactions lt JOIN ledger_entries le ON le.ledger_transaction_id=lt.id JOIN LATERAL(SELECT COALESCE(SUM(amount_minor) FILTER(WHERE entry_type='DEBIT'),0) debits,COALESCE(SUM(amount_minor) FILTER(WHERE entry_type='CREDIT'),0) credits FROM ledger_entries WHERE ledger_transaction_id=lt.id)x ON TRUE`),
      this.database.query(`SELECT currency,COALESCE(SUM(amount_minor) FILTER(WHERE entry_type='DEBIT'),0)::TEXT AS debits,COALESCE(SUM(amount_minor) FILTER(WHERE entry_type='CREDIT'),0)::TEXT AS credits,(COALESCE(SUM(amount_minor) FILTER(WHERE entry_type='DEBIT'),0)-COALESCE(SUM(amount_minor) FILTER(WHERE entry_type='CREDIT'),0))::TEXT AS difference FROM ledger_entries GROUP BY currency ORDER BY currency`),
      this.database.query(`SELECT le.id,le.entry_type,le.amount_minor::TEXT,le.currency,le.created_at,lt.id AS transaction_id,lt.transaction_type,lt.reference_id,lt.description,lt.reversal_of_id,lt.posted_at,la.id AS account_id,la.account_code,la.account_type,la.name AS account_name,la.wallet_id FROM ledger_entries le JOIN ledger_transactions lt ON lt.id=le.ledger_transaction_id JOIN ledger_accounts la ON la.id=le.ledger_account_id WHERE($1='' OR upper(lt.reference_id::TEXT)=upper($1) OR upper(la.account_code)=upper($1) OR upper(lt.id::TEXT)=upper($1))AND($2::TEXT IS NULL OR le.entry_type::TEXT=$2)AND($3::TEXT IS NULL OR le.currency=$3)AND($4::UUID IS NULL OR la.id=$4)ORDER BY lt.posted_at DESC,le.id DESC LIMIT 100`,[search,query.entryType??null,query.currency?.toUpperCase()??null,query.accountId??null]),
      this.database.query(`SELECT w.id,w.wallet_number,w.currency,w.balance_minor::TEXT AS operational_balance,COALESCE(SUM(CASE le.entry_type WHEN 'CREDIT' THEN le.amount_minor ELSE -le.amount_minor END),0)::TEXT AS ledger_balance,(w.balance_minor-COALESCE(SUM(CASE le.entry_type WHEN 'CREDIT' THEN le.amount_minor ELSE -le.amount_minor END),0))::TEXT AS difference,u.full_name FROM wallets w JOIN users u ON u.id=w.user_id LEFT JOIN ledger_accounts la ON la.wallet_id=w.id AND la.account_type='USER_WALLET' LEFT JOIN ledger_entries le ON le.ledger_account_id=la.id GROUP BY w.id,u.full_name HAVING w.balance_minor<>COALESCE(SUM(CASE le.entry_type WHEN 'CREDIT' THEN le.amount_minor ELSE -le.amount_minor END),0) ORDER BY abs(w.balance_minor-COALESCE(SUM(CASE le.entry_type WHEN 'CREDIT' THEN le.amount_minor ELSE -le.amount_minor END),0)) DESC LIMIT 50`),
      this.database.query(`SELECT rr.*,u.full_name AS initiated_by FROM reconciliation_runs rr LEFT JOIN users u ON u.id=rr.initiated_by_user_id ORDER BY rr.created_at DESC LIMIT 30`),
      this.database.query(`SELECT rf.*,w.wallet_number,t.transfer_reference,la.account_code,COALESCE(resolver.full_name,'') AS resolved_by FROM reconciliation_findings rf LEFT JOIN wallets w ON w.id=rf.wallet_id LEFT JOIN transfers t ON t.id=rf.transfer_id LEFT JOIN ledger_accounts la ON la.id=rf.ledger_account_id LEFT JOIN users resolver ON resolver.id=rf.resolved_by_user_id ORDER BY rf.detected_at DESC LIMIT 100`),
      this.database.query(`SELECT ar.*,requester.full_name AS requested_by,approver.full_name AS approved_by,rejector.full_name AS rejected_by,COALESCE(json_agg(json_build_object('id',al.id,'ledgerAccountId',al.ledger_account_id,'accountCode',la.account_code,'entryType',al.entry_type,'amountMinor',al.amount_minor::TEXT,'currency',al.currency,'description',al.description)) FILTER(WHERE al.id IS NOT NULL),'[]') AS lines FROM ledger_adjustment_requests ar JOIN users requester ON requester.id=ar.requested_by_user_id LEFT JOIN users approver ON approver.id=ar.approved_by_user_id LEFT JOIN users rejector ON rejector.id=ar.rejected_by_user_id LEFT JOIN ledger_adjustment_lines al ON al.adjustment_request_id=ar.id LEFT JOIN ledger_accounts la ON la.id=al.ledger_account_id GROUP BY ar.id,requester.full_name,approver.full_name,rejector.full_name ORDER BY ar.created_at DESC LIMIT 50`),
      this.database.query(`SELECT id,account_code,account_type,name,currency,status,wallet_id FROM ledger_accounts ORDER BY account_type,account_code`)
    ]);
    return {summary:summary.rows[0],trialBalance:trial.rows,entries:entries.rows,walletMismatches:wallets.rows,runs:runs.rows,findings:findings.rows,adjustments:adjustments.rows,accounts:accounts.rows};
  }

  async startRun(adminId:string,role:Role,dto:StartReconciliationDto){
    await this.assertAdmin(this.database,adminId,role); const client=await this.database.connect(); const runId=randomUUID(); const asOf=new Date();
    try{await client.query("BEGIN");await client.query(`INSERT INTO reconciliation_runs(id,run_type,scope_currency,scope_wallet_id,status,trigger_source,initiated_by_user_id,as_of_time,started_at)VALUES($1,$2,$3,$4,'RUNNING','ADMIN',$5,$6,$6)`,[runId,dto.runType,dto.currency?.toUpperCase()??null,dto.walletId??null,adminId,asOf]);
      const findings=await this.detect(client,dto,asOf); for(const finding of findings.rows){await client.query(`INSERT INTO reconciliation_findings(id,reconciliation_run_id,finding_type,severity,currency,wallet_id,transfer_id,funding_transaction_id,ledger_transaction_id,ledger_account_id,expected_amount_minor,actual_amount_minor,difference_minor,evidence)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::JSONB)`,[randomUUID(),runId,finding.finding_type,finding.severity,finding.currency,finding.wallet_id,finding.transfer_id,finding.funding_transaction_id,finding.ledger_transaction_id,finding.ledger_account_id,finding.expected_amount_minor,finding.actual_amount_minor,finding.difference_minor,JSON.stringify(finding.evidence)]);}
      await client.query(`UPDATE reconciliation_runs SET status='COMPLETED',records_checked=$2,finding_count=$3,completed_at=NOW(),updated_at=NOW() WHERE id=$1`,[runId,findings.checked,findings.rows.length]);await this.audit(client,adminId,"RECONCILIATION_RUN_COMPLETED","RECONCILIATION_RUN",runId,{runType:dto.runType,recordsChecked:findings.checked,findings:findings.rows.length});await client.query("COMMIT");return {id:runId,status:"COMPLETED",recordsChecked:findings.checked,findingCount:findings.rows.length};
    }catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}
  }

  private async detect(client:PoolClient,dto:StartReconciliationDto,asOf:Date){
    const currency=dto.currency?.toUpperCase()??null; const wallet=dto.walletId??null; let result;
    if(dto.runType==="GLOBAL_TRIAL_BALANCE") result=await client.query(`SELECT 'GLOBAL_TRIAL_BALANCE_MISMATCH' finding_type,'CRITICAL' severity,le.currency,NULL::UUID wallet_id,NULL::UUID transfer_id,NULL::UUID funding_transaction_id,NULL::UUID ledger_transaction_id,NULL::UUID ledger_account_id,SUM(amount_minor) FILTER(WHERE entry_type='DEBIT')::BIGINT expected_amount_minor,SUM(amount_minor) FILTER(WHERE entry_type='CREDIT')::BIGINT actual_amount_minor,(SUM(amount_minor) FILTER(WHERE entry_type='DEBIT')-SUM(amount_minor) FILTER(WHERE entry_type='CREDIT'))::BIGINT difference_minor,jsonb_build_object('debitTotal',SUM(amount_minor) FILTER(WHERE entry_type='DEBIT'),'creditTotal',SUM(amount_minor) FILTER(WHERE entry_type='CREDIT')) evidence FROM ledger_entries le WHERE le.created_at<=$1 AND($2::TEXT IS NULL OR le.currency=$2)GROUP BY le.currency HAVING SUM(amount_minor) FILTER(WHERE entry_type='DEBIT')<>SUM(amount_minor) FILTER(WHERE entry_type='CREDIT')`,[asOf,currency]);
    else if(dto.runType==="LEDGER_TRANSACTION_BALANCE") result=await client.query(`SELECT 'UNBALANCED_LEDGER_TRANSACTION' finding_type,'CRITICAL' severity,le.currency,NULL::UUID wallet_id,NULL::UUID transfer_id,NULL::UUID funding_transaction_id,lt.id ledger_transaction_id,NULL::UUID ledger_account_id,SUM(amount_minor) FILTER(WHERE entry_type='DEBIT')::BIGINT expected_amount_minor,SUM(amount_minor) FILTER(WHERE entry_type='CREDIT')::BIGINT actual_amount_minor,(SUM(amount_minor) FILTER(WHERE entry_type='DEBIT')-SUM(amount_minor) FILTER(WHERE entry_type='CREDIT'))::BIGINT difference_minor,jsonb_build_object('transactionType',lt.transaction_type,'referenceId',lt.reference_id) evidence FROM ledger_transactions lt JOIN ledger_entries le ON le.ledger_transaction_id=lt.id WHERE lt.posted_at<=$1 AND($2::TEXT IS NULL OR le.currency=$2)GROUP BY lt.id,le.currency HAVING SUM(amount_minor) FILTER(WHERE entry_type='DEBIT')<>SUM(amount_minor) FILTER(WHERE entry_type='CREDIT')`,[asOf,currency]);
    else if(dto.runType==="WALLET_BALANCE") result=await client.query(`SELECT 'WALLET_BALANCE_MISMATCH' finding_type,'HIGH' severity,w.currency,w.id wallet_id,NULL::UUID transfer_id,NULL::UUID funding_transaction_id,NULL::UUID ledger_transaction_id,la.id ledger_account_id,w.balance_minor::BIGINT expected_amount_minor,COALESCE(SUM(CASE le.entry_type WHEN 'CREDIT' THEN le.amount_minor ELSE -le.amount_minor END),0)::BIGINT actual_amount_minor,(w.balance_minor-COALESCE(SUM(CASE le.entry_type WHEN 'CREDIT' THEN le.amount_minor ELSE -le.amount_minor END),0))::BIGINT difference_minor,jsonb_build_object('walletNumber',w.wallet_number,'asOf',$1::TIMESTAMPTZ) evidence FROM wallets w LEFT JOIN ledger_accounts la ON la.wallet_id=w.id AND la.account_type='USER_WALLET' LEFT JOIN ledger_entries le ON le.ledger_account_id=la.id AND le.created_at<=$1 WHERE($2::TEXT IS NULL OR w.currency=$2)AND($3::UUID IS NULL OR w.id=$3)GROUP BY w.id,la.id HAVING w.balance_minor<>COALESCE(SUM(CASE le.entry_type WHEN 'CREDIT' THEN le.amount_minor ELSE -le.amount_minor END),0)`,[asOf,currency,wallet]);
    else if(dto.runType==="TRANSFER_POSTING") result=await client.query(`WITH p AS(SELECT t.*,COUNT(DISTINCT lt.id) posting_count,COALESCE(SUM(le.amount_minor) FILTER(WHERE le.entry_type='DEBIT'),0) debits,COALESCE(SUM(le.amount_minor) FILTER(WHERE le.entry_type='CREDIT'),0) credits FROM transfers t LEFT JOIN ledger_transactions lt ON lt.reference_id=t.id AND lt.transaction_type='WALLET_TRANSFER' LEFT JOIN ledger_entries le ON le.ledger_transaction_id=lt.id WHERE t.created_at<=$1 AND($2::TEXT IS NULL OR t.currency=$2)GROUP BY t.id)SELECT CASE WHEN status IN('COMPLETED','REVERSED')AND posting_count=0 THEN 'MISSING_TRANSFER_POSTING' WHEN posting_count>1 THEN 'DUPLICATE_TRANSFER_POSTING' WHEN status NOT IN('COMPLETED','REVERSED')AND posting_count>0 THEN 'UNEXPECTED_TRANSFER_POSTING' ELSE 'TRANSFER_AMOUNT_MISMATCH' END finding_type,CASE WHEN posting_count=0 THEN 'CRITICAL' ELSE 'HIGH' END severity,currency,NULL::UUID wallet_id,id transfer_id,NULL::UUID funding_transaction_id,NULL::UUID ledger_transaction_id,NULL::UUID ledger_account_id,amount_minor::BIGINT expected_amount_minor,debits::BIGINT actual_amount_minor,(amount_minor-debits)::BIGINT difference_minor,jsonb_build_object('reference',transfer_reference,'status',status,'postingCount',posting_count,'debits',debits,'credits',credits) evidence FROM p WHERE(status IN('COMPLETED','REVERSED')AND(posting_count<>1 OR debits<>amount_minor OR credits<>amount_minor))OR(status NOT IN('COMPLETED','REVERSED')AND posting_count>0)`,[asOf,currency]);
    else result=await client.query(`WITH p AS(SELECT f.*,COUNT(DISTINCT lt.id) posting_count,COALESCE(SUM(le.amount_minor) FILTER(WHERE le.entry_type='CREDIT' AND la.wallet_id=f.wallet_id),0) wallet_credits FROM funding_transactions f LEFT JOIN ledger_transactions lt ON lt.reference_id=f.id AND lt.transaction_type='WALLET_FUNDING' LEFT JOIN ledger_entries le ON le.ledger_transaction_id=lt.id LEFT JOIN ledger_accounts la ON la.id=le.ledger_account_id WHERE f.created_at<=$1 AND($2::TEXT IS NULL OR f.currency=$2)GROUP BY f.id)SELECT CASE WHEN posting_count=0 THEN 'MISSING_FUNDING_POSTING' ELSE 'DUPLICATE_FUNDING_POSTING' END finding_type,'HIGH' severity,currency,wallet_id,NULL::UUID transfer_id,id funding_transaction_id,NULL::UUID ledger_transaction_id,NULL::UUID ledger_account_id,amount_minor::BIGINT expected_amount_minor,wallet_credits::BIGINT actual_amount_minor,(amount_minor-wallet_credits)::BIGINT difference_minor,jsonb_build_object('status',status,'postingCount',posting_count,'walletCredits',wallet_credits) evidence FROM p WHERE(status='COMPLETED'AND(posting_count<>1 OR wallet_credits<>amount_minor))`,[asOf,currency]);
    const count=await this.scopeCount(client,dto,asOf); return {rows:result.rows,checked:count};
  }
  private async scopeCount(client:PoolClient,dto:StartReconciliationDto,asOf:Date){const table=dto.runType==="WALLET_BALANCE"?"wallets":dto.runType==="TRANSFER_POSTING"?"transfers":dto.runType==="FUNDING_POSTING"?"funding_transactions":dto.runType==="LEDGER_TRANSACTION_BALANCE"?"ledger_transactions":"ledger_entries";const result=await client.query(`SELECT COUNT(*)::INT count FROM ${table} WHERE created_at<=$1`,[asOf]);return result.rows[0].count as number}

  async updateFinding(adminId:string,role:Role,id:string,dto:FindingActionDto){this.uuid(id);await this.assertAdmin(this.database,adminId,role);const result=await this.database.query(`UPDATE reconciliation_findings SET status=$2,resolution_note=$3,resolved_by_user_id=$4,resolved_at=CASE WHEN $2='UNDER_REVIEW' THEN NULL ELSE NOW() END,updated_at=NOW() WHERE id=$1 AND status IN('OPEN','UNDER_REVIEW') RETURNING id,status`,[id,dto.status,dto.resolutionNote,adminId]);if(!result.rows[0])throw new ConflictException("Finding is not open for this transition.");return result.rows[0]}

  async createAdjustment(adminId:string,role:Role,dto:CreateAdjustmentDto){await this.assertAdmin(this.database,adminId,role);const client=await this.database.connect();try{await client.query("BEGIN");await this.validateLines(client,dto.currency,dto.lines);const id=randomUUID(),reference=`LFADJ${Date.now().toString(36).toUpperCase()}${randomBytes(3).toString("hex").toUpperCase()}`.slice(0,24);await client.query(`INSERT INTO ledger_adjustment_requests(id,adjustment_reference,finding_id,adjustment_type,target_ledger_transaction_id,currency,reason_code,reason,requested_by_user_id)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,reference,dto.findingId??null,dto.adjustmentType,dto.targetLedgerTransactionId??null,dto.currency.toUpperCase(),dto.reasonCode.toUpperCase(),dto.reason,adminId]);for(const line of dto.lines)await client.query(`INSERT INTO ledger_adjustment_lines(id,adjustment_request_id,ledger_account_id,entry_type,amount_minor,currency,description)VALUES($1,$2,$3,$4,$5,$6,$7)`,[randomUUID(),id,line.ledgerAccountId,line.entryType,line.amountMinor,dto.currency.toUpperCase(),line.description??null]);await this.audit(client,adminId,"LEDGER_ADJUSTMENT_DRAFT_CREATED","LEDGER_ADJUSTMENT",id,{reference});await client.query("COMMIT");return{id,reference,status:"DRAFT"}}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
  async submitAdjustment(adminId:string,role:Role,id:string){this.uuid(id);await this.assertAdmin(this.database,adminId,role);const client=await this.database.connect();try{await client.query("BEGIN");const request=await this.request(client,id,true);if(request.status!=="DRAFT"||request.requested_by_user_id!==adminId)throw new ConflictException("Only the requester can submit this draft.");const lines=await this.lines(client,id);await this.validateLines(client,request.currency,lines.map((x:any)=>({ledgerAccountId:x.ledger_account_id,entryType:x.entry_type,amountMinor:Number(x.amount_minor)})));await client.query(`UPDATE ledger_adjustment_requests SET status='PENDING_APPROVAL',updated_at=NOW() WHERE id=$1`,[id]);await this.audit(client,adminId,"LEDGER_ADJUSTMENT_SUBMITTED","LEDGER_ADJUSTMENT",id,{});await client.query("COMMIT");return{id,status:"PENDING_APPROVAL"}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
  async decideAdjustment(adminId:string,role:Role,id:string,decision:"APPROVED"|"REJECTED",dto:AdjustmentDecisionDto){this.uuid(id);await this.assertAdmin(this.database,adminId,role);const result=await this.database.query(`UPDATE ledger_adjustment_requests SET status=$2,approved_by_user_id=CASE WHEN $2='APPROVED' THEN $3 ELSE NULL END,approved_at=CASE WHEN $2='APPROVED' THEN NOW() ELSE NULL END,rejected_by_user_id=CASE WHEN $2='REJECTED' THEN $3 ELSE NULL END,rejected_at=CASE WHEN $2='REJECTED' THEN NOW() ELSE NULL END,resolution_note=$4,updated_at=NOW() WHERE id=$1 AND status='PENDING_APPROVAL' AND requested_by_user_id<>$3 RETURNING id,status`,[id,decision,adminId,dto.resolutionNote]);if(!result.rows[0])throw new ConflictException("A different administrator must decide a pending request.");return result.rows[0]}
  async cancelAdjustment(adminId:string,role:Role,id:string){this.uuid(id);await this.assertAdmin(this.database,adminId,role);const result=await this.database.query(`UPDATE ledger_adjustment_requests SET status='CANCELLED',updated_at=NOW() WHERE id=$1 AND status='DRAFT' AND requested_by_user_id=$2 RETURNING id,status`,[id,adminId]);if(!result.rows[0])throw new ConflictException("Only your own draft can be cancelled.");return result.rows[0]}
  async executeAdjustment(adminId:string,role:Role,id:string){this.uuid(id);await this.assertAdmin(this.database,adminId,role);const client=await this.database.connect();try{await client.query("BEGIN");const request=await this.request(client,id,true);if(request.status!=="APPROVED")throw new ConflictException("Only an approved adjustment can execute.");const lines=await this.lines(client,id);await this.validateLines(client,request.currency,lines.map((x:any)=>({ledgerAccountId:x.ledger_account_id,entryType:x.entry_type,amountMinor:Number(x.amount_minor)})));const walletEffects=new Map<string,bigint>();for(const line of lines){if(line.wallet_id){const effect=(line.entry_type==="CREDIT"?1n:-1n)*BigInt(line.amount_minor);walletEffects.set(line.wallet_id,(walletEffects.get(line.wallet_id)??0n)+effect)}}for(const [walletId,effect]of walletEffects){const locked=await client.query(`SELECT balance_minor FROM wallets WHERE id=$1 FOR UPDATE`,[walletId]);if(!locked.rows[0]||BigInt(locked.rows[0].balance_minor)+effect<0n)throw new BadRequestException("Adjustment would make a wallet balance negative.")}
      const transactionId=randomUUID();await client.query(`INSERT INTO ledger_transactions(id,transaction_type,reference_id,description)VALUES($1,'LEDGER_ADJUSTMENT',$2,$3)`,[transactionId,id,`Ledger adjustment ${request.adjustment_reference}`]);for(const line of lines)await client.query(`INSERT INTO ledger_entries(id,ledger_transaction_id,ledger_account_id,entry_type,amount_minor,currency)VALUES($1,$2,$3,$4,$5,$6)`,[randomUUID(),transactionId,line.ledger_account_id,line.entry_type,line.amount_minor,request.currency]);for(const[walletId,effect]of walletEffects)await client.query(`UPDATE wallets SET balance_minor=balance_minor+$2,updated_at=NOW() WHERE id=$1`,[walletId,effect.toString()]);await client.query(`UPDATE ledger_adjustment_requests SET status='EXECUTED',executed_ledger_transaction_id=$2,executed_at=NOW(),updated_at=NOW() WHERE id=$1`,[id,transactionId]);if(request.finding_id)await client.query(`UPDATE reconciliation_findings SET status='RESOLVED',resolution_note=COALESCE(resolution_note,'Resolved by approved ledger adjustment'),resolved_by_user_id=$2,resolved_at=NOW(),updated_at=NOW() WHERE id=$1 AND status IN('OPEN','UNDER_REVIEW')`,[request.finding_id,adminId]);await this.audit(client,adminId,"LEDGER_ADJUSTMENT_EXECUTED","LEDGER_ADJUSTMENT",id,{transactionId});await client.query("COMMIT");return{id,status:"EXECUTED",ledgerTransactionId:transactionId}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}

  private async validateLines(client:PoolClient,currency:string,lines:{ledgerAccountId:string;entryType:string;amountMinor:number}[]){if(lines.length<2)throw new BadRequestException("At least two lines are required.");const debit=lines.filter(x=>x.entryType==="DEBIT").reduce((n,x)=>n+BigInt(x.amountMinor),0n),credit=lines.filter(x=>x.entryType==="CREDIT").reduce((n,x)=>n+BigInt(x.amountMinor),0n);if(debit===0n||debit!==credit)throw new BadRequestException("Adjustment debit and credit totals must be equal.");const ids=[...new Set(lines.map(x=>x.ledgerAccountId))];const accounts=await client.query(`SELECT id FROM ledger_accounts WHERE id=ANY($1::UUID[]) AND currency=$2 AND status='ACTIVE'`,[ids,currency.toUpperCase()]);if(accounts.rows.length!==ids.length)throw new BadRequestException("Every adjustment account must be active and use the request currency.")}
  private request(client:PoolClient,id:string,lock=false){return client.query(`SELECT * FROM ledger_adjustment_requests WHERE id=$1${lock?" FOR UPDATE":""}`,[id]).then(r=>{if(!r.rows[0])throw new NotFoundException("Adjustment request not found.");return r.rows[0]})}
  private lines(client:PoolClient,id:string){return client.query(`SELECT al.*,la.wallet_id FROM ledger_adjustment_lines al JOIN ledger_accounts la ON la.id=al.ledger_account_id WHERE adjustment_request_id=$1 ORDER BY al.created_at,al.id`,[id]).then(r=>r.rows)}
  private async audit(client:PoolClient,actor:string,action:string,resourceType:string,resourceId:string,metadata:Record<string,unknown>){await client.query(`INSERT INTO audit_records(id,deduplication_key,actor_type,actor_user_id,actor_reference,action_type,resource_type,resource_id,outcome,severity,source_type,metadata,occurred_at)VALUES($1,$2,'ADMIN',$3::UUID,$3::TEXT,$4,$5,$6,'SUCCESS','INFO','ADMIN_API',$7::JSONB,NOW())`,[randomUUID(),`${action}:${resourceId}:${randomUUID()}`,actor,action,resourceType,resourceId,JSON.stringify(metadata)])}
  private async assertAdmin(db:DatabaseService|PoolClient,id:string,role:Role){if(role!=="ADMIN")throw new ForbiddenException("Administrator access required.");const sql=`SELECT 1 FROM users WHERE id=$1 AND role='ADMIN' AND status='ACTIVE'`;const result=db instanceof DatabaseService?await db.query(sql,[id]):await db.query(sql,[id]);if(!result.rows[0])throw new ForbiddenException("Active administrator access required.")}
  private uuid(id:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))throw new BadRequestException("Invalid identifier.")}
}
